apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tasks-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
      - name: tasks-app
        image: yanishlali/node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
