apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/yanis/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Dec 2024 09:00:15 CET
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 03 Dec 2024 09:00:15 CET
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/yanis/.minikube/profiles/minikube/client.crt
    client-key: /home/yanis/.minikube/profiles/minikube/client.key
