groups:
  - name: alert.rules
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total[2m])) by (pod) > 0.8
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{ $labels.pod }} has high CPU usage"
          description: "CPU usage is above 80% for pod {{ $labels.pod }} for 1 minute."
