name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Docker Buildx pour le build multi-plateforme
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Se connecter à DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build et Push de l'image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yanishlali/node-app:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de kubectl avec la clé kubeconfig depuis les secrets
      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      # Etape pour configurer SSH et établir un tunnel
      - name: Set up SSH for tunnel
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Vérification et création du répertoire ~/.ssh avec les bonnes permissions
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh  # Fixer les permissions du répertoire

          # Vérification du contenu du répertoire .ssh
          ls -la $HOME/.ssh

          # Ajouter la clé privée SSH avec les bonnes permissions
          echo "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa  # Fixer les permissions du fichier de clé privée

          # Ajouter la clé d'hôte de la machine distante (pour éviter les problèmes de "host verification")
          ssh-keyscan -H 192.168.1.100 >> $HOME/.ssh/known_hosts

          # Débogage : Vérifier que la clé privée est correctement écrite (sans l'afficher)
          echo "SSH_PRIVATE_KEY set" 

          # Etablir le tunnel SSH en arrière-plan
          nohup ssh -N -L 8080:192.168.49.2:31543 ubuntu@192.168.1.100 &

          # Attente de 5 secondes pour s'assurer que le tunnel SSH est configuré
          sleep 5

      # Appliquer les manifests Kubernetes pour déployer l'application
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s/deployment.yaml --validate=false
          kubectl apply -f ./k8s/service.yaml
          kubectl apply -f ./k8s/hpa.yaml
