name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yanishlali/node-app:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Set up SSH for tunnel
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Création du répertoire .ssh
          mkdir -p ~/.ssh
          # Ajouter la clé privée SSH
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Ajouter la clé d'hôte de la machine distante (pour éviter les problèmes de "host verification")
          ssh-keyscan -H 192.168.1.100 >> ~/.ssh/known_hosts
          # Etablir le tunnel SSH
          ssh -N -L 8080:192.168.49.2:31543 ubuntu@192.168.1.100 &

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s/deployment.yaml --validate=false
          kubectl apply -f ./k8s/service.yaml
          kubectl apply -f ./k8s/hpa.yaml
