name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug file structure
        run: ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yanishlali/node-app:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug file structure
        run: ls -R

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Delete existing Kind clusters (if any)
        run: kind delete cluster || true

      - name: Create Kubernetes cluster with Kind
        run: kind create cluster

      - name: Set up kubectl for Kind
        run: |
          mkdir -p $HOME/.kube
          kind get kubeconfig > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml

      - name: Apply Alerting Rules to Prometheus
        run: |
          helm upgrade prometheus prometheus-community/kube-prometheus-stack \
            --reuse-values \
            --set prometheusRule.additionalRulesEnabled=true \
            --set-file prometheusRule.additionalRules=k8s/alerting-rules.yaml

      - name: Verify Kubernetes resources
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get hpa
