name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Étape 2 : Vérifier la structure des fichiers (debug)
      - name: Debug file structure
        run: ls -R

      # Étape 3 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 4 : Connexion à Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 5 : Construire et pousser l'image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yanishlali/node-app:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Étape 2 : Vérifier la structure des fichiers (debug)
      - name: Debug file structure
        run: ls -R

      # Étape 3 : Vérifier le dossier k8s (debug avancé)
      - name: Check k8s directory
        run: |
          if [ -d "./k8s" ]; then
            echo "k8s directory exists!"
            ls ./k8s
          else
            echo "k8s directory is missing!"
            exit 1
          fi

      # Étape 4 : Installer Kind
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Étape 5 : Créer un cluster Kubernetes avec Kind
      - name: Create Kubernetes cluster with Kind
        run: kind create cluster

      # Étape 6 : Configurer kubectl pour Kind
      - name: Set up kubectl for Kind
        run: |
          mkdir -p $HOME/.kube
          kind get kubeconfig > $HOME/.kube/config

      # Étape 7 : Appliquer les manifests Kubernetes
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s/deployment.yaml
          kubectl apply -f ./k8s/service.yaml

      # Étape 8 : Vérifier les ressources Kubernetes
      - name: Verify Kubernetes resources
        run: |
          kubectl get pods
          kubectl get svc
